// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwBbHSFvkT3xG-h6LEqdZPhdj49GByHEQ',
    appId: '1:1034764408533:web:8b582aebbfb355887bf45c',
    messagingSenderId: '1034764408533',
    projectId: 'test-samplewebapp-on-firebase',
    authDomain: 'test-samplewebapp-on-firebase.firebaseapp.com',
    storageBucket: 'test-samplewebapp-on-firebase.appspot.com',
    measurementId: 'G-0E8W2CQ4N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZO2tqhIxUBk-UmBmpuG7ppTMwO14EakQ',
    appId: '1:1034764408533:android:af874748416135a87bf45c',
    messagingSenderId: '1034764408533',
    projectId: 'test-samplewebapp-on-firebase',
    storageBucket: 'test-samplewebapp-on-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeAnWQM5rq3ihfQaISDugSMoh4OYtTmbA',
    appId: '1:1034764408533:ios:2fb694b6ab92f4c37bf45c',
    messagingSenderId: '1034764408533',
    projectId: 'test-samplewebapp-on-firebase',
    storageBucket: 'test-samplewebapp-on-firebase.appspot.com',
    iosClientId: '1034764408533-plp9nudhfohio83ljeh3cq6sjh74tg41.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleWebappOnFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeAnWQM5rq3ihfQaISDugSMoh4OYtTmbA',
    appId: '1:1034764408533:ios:b560f6084c8123f67bf45c',
    messagingSenderId: '1034764408533',
    projectId: 'test-samplewebapp-on-firebase',
    storageBucket: 'test-samplewebapp-on-firebase.appspot.com',
    iosClientId: '1034764408533-2f3276fmpk77d21237dd5hhe6dmbsna8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleWebappOnFirebase.RunnerTests',
  );
}
